In [87]:
import numpy as np
a = np.ones((4,3),dtype=int)
print(a)
b = np.zeros((3,3),dtype=int)
print(b)
print(b.shape)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
(3, 3)


In [23]:
j = np.random.randint(1,10 ,size=(3,5),dtype=int)
print(j)

[[1 8 3 5 8]
 [2 6 4 1 4]
 [5 9 1 4 1]]


In [30]:
a = np.identity(4,dtype=int)
print(a)
mean = a.mean()
print(mean)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
0.25


In [35]:
a = np.random.randint(1,8, size=(3,3), dtype=int)
x = np.identity(3,dtype=int)
print(x)
y = np.pad(x,1)
print(y)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]


In [55]:
dim = eval(input("ENTER THE DIMENSION:-"))
a = np.zeros((dim,dim),dtype=int)
a[::2,1::2]=1
a[1::2,::2]=1
print(a)

ENTER THE DIMENSION:-8
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [168]:
a = np.array([[1,2,3],[4,5,6]])
x = np.array(((1,2,3),(2,3,4)))
print(x)
a[0,1]=55
a.reshape(3,2)
print(a)
print(a[0,1]) 
print(a.size)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.data)

[[1 2 3]
 [2 3 4]]
[[ 1 55  3]
 [ 4  5  6]]
55
6
(2, 3)
int64
2


In [113]:
a = np.arange(0,100,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [147]:
dict = {'Theodore':19,'Roxanne':22,'Mathew':21,'Betty':20}
print(max(dict, key=dict.get),end=(" "))
print(min(dict, key=dict.get),end=(" "))


Roxanne Theodore 

In [4]:
a = np.random.randint(1,4,size=(4,4),dtype="int")
print(a)
b = np.identity(4)
print(b)
n = np.pad(b,1)
print(n)
x = np.add(a,b)
x = np.multiply(a,b)
# x = np.divide(a,b)
x = np.sqrt(a)
x = np.exp(b)
x = np.subtract(a,b)
x = a.sum()
x = a.T
print(x)

[[1 2 3 2]
 [3 2 3 1]
 [2 2 1 2]
 [2 3 2 2]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1 3 2 2]
 [2 2 2 3]
 [3 3 1 2]
 [2 1 2 2]]


In [15]:
x = [[1,2,3,4],[2,3,4,5],[9,7,6,5]]
a = np.array(x)
print(a)
a.ndim
a.size
x = a.reshape(4,3)
print(x)
x.shape
x.T
x.sum()
x.mean()
x.argmax(axis=0)
x.argmin(axis=1)
x.argsort(axis=0)
x.ravel()
x.min()
x.max()
np.where(x>5)
b =x.sort()
print(x)



[[1 2 3 4]
 [2 3 4 5]
 [9 7 6 5]]
[[1 2 3]
 [4 2 3]
 [4 5 9]
 [7 6 5]]
[[1 2 3]
 [2 3 4]
 [4 5 9]
 [5 6 7]]


In [8]:
import numpy as np
x= []
for e in range(2):
    i = int(input("ENTER THE ELEMENT FOR ARRAY:-"))
    x.append(i)
y = np.array(x)
print(y) 
print(np.all(y))


ENTER THE ELEMENT FOR ARRAY:-0
ENTER THE ELEMENT FOR ARRAY:-2
[0 2]
False
